# Generated by Django 3.0.3 on 2020-04-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200411_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='accounts/user_default.gif', upload_to=''),
        ),
    ]
