# Generated by Django 3.0.3 on 2020-03-27 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(default='', upload_to='')),
            ],
            options={
                'unique_together': {('id', 'picture')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=255)),
                ('date_time', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact1', models.CharField(max_length=255)),
                ('contact2', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.AssetType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
