# Generated by Django 3.0.3 on 2020-04-25 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('found', 'เจอของหาย'), ('lost', 'ตามหาของ')], default='found', max_length=255)),
                ('date_time', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact1', models.CharField(max_length=255)),
                ('contact2', models.CharField(max_length=255)),
                ('key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('take_information', models.CharField(blank=True, max_length=255, null=True)),
                ('assetType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.AssetType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='posts/post_default.gif', upload_to='posts/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
