# Generated by Django 3.0.3 on 2020-03-26 17:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpicture',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='postpicture',
            name='id',
            field=models.ForeignKey(default=uuid.uuid4, editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.Post'),
        ),
    ]
