# Generated by Django 3.0.3 on 2020-03-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200327_0013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postpicture',
            unique_together={('id', 'picture')},
        ),
    ]
