# Generated by Django 3.0.3 on 2020-04-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200403_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('lost', 'ตามหาของ'), ('found', 'เจอของหาย')], max_length=255),
        ),
    ]
