# Generated by Django 3.0.3 on 2020-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200411_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpicture',
            name='picture',
            field=models.ImageField(default='posts/default.png', upload_to=''),
        ),
    ]
