# Generated by Django 3.0.3 on 2020-04-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200417_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpicture',
            name='picture',
            field=models.ImageField(default='posts/default.png', upload_to='posts/'),
        ),
    ]
