# Generated by Django 3.0.3 on 2020-04-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200417_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('found', 'เจอของหาย'), ('lost', 'ตามหาของ')], default='found', max_length=255),
        ),
    ]
