# Generated by Django 3.0.3 on 2020-04-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200417_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpicture',
            name='picture',
            field=models.ImageField(default='posts/post_default.gif', upload_to='posts/'),
        ),
    ]
