# Generated by Django 3.0.3 on 2020-04-22 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200419_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpicture',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postpicture', to='posts.Post'),
        ),
    ]
