# Generated by Django 3.0.3 on 2020-04-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200422_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='take_information',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
