# Generated by Django 3.0.3 on 2020-04-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_take_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='take_information',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
